version: "3"

services:
  webapi:
    image: docker-dotnetcore/webapi:develop
    build:
      context: ../WebApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  client:
    image: docker-dotnetcore/client:develop
    build:
      context: ../Client
      dockerfile: Dockerfile
    depends_on:
      - webapi
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"    
